language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.5.9
      env: setup=lowest
    - php: 5.5.9
      env: setup=stable

sudo: false

before_install:
  - travis_retry composer self-update
  - touch ./storage/database.sqlite

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

before_script:
  - cp .env.example .env
  - php artisan key:generate
  - php artisan api:key-generate
  - php artisan module:publish
  - php artisan stylist:publish
  - touch ./storage/app/installed


script: vendor/bin/phpunit