language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer self-update
  - composer create-project societycms/societycms
  - cd ./societycms
  - touch ./storage/database.sqlite
  - export APP_ENV="testing"

script: "phpunit"